title: "Encuestas La Cosa Nostra"
description: "Sitio institucional para publicar encuestas, hist칩rico y videos."
url: "" # Setear dominio de producci칩n
baseurl: "" # Subcarpeta si aplica
lang: es
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "encuestas"
    values:
      layout: "encuesta"

collections:
  encuestas:
    output: true
    permalink: "/encuestas/:title/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

# jekyll-paginate-v2 para paginar colecci칩n encuestas
pagination:
  enabled: true
  debug: false
  collection: 'encuestas'
  per_page: 4
  permalink: '/encuestas/page/:num/'
  title: ':title - P치gina :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Datos del sitio
social:
  twitter: ""
  linkedin: ""
  facebook: ""
  youtube: ""
